from . import approval_category_inherit
from . import approval_request_inherit
from . import hr_job_inherit
from . import hr_skill_inherit
from . import hr_skill_level_inherit
from . import hr_applicant_evaluation_form
from . import hr_applicant_inherit
from . import hr_appraisal_inherit
from . import hr_employee_inherit
from . import hr_employee_public_inherit
from . import recruitment_approval_stage
from . import hr_department_inherit